language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  python setup.py develop
before_script: mkdir -p shippable/codecoverage shippable/testresults
script:
  - coverage run --source=coveralls setup.py test
  - coverage xml -o shippable/codecoverage/coverage.xml setup.py
  
after_script:
  coveralls --verbose
